import Head from 'next/head';

export default function Home() {
    return (
        <>
            <Head>
                <title>Storybook + Nextjs + Firebase</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=" flex items-center justify-center h-screen">
                <h1 className="uppercase text-5xl font-bold font-lombok">
                    CraftConnect
                </h1>
                {/* <h1 className="uppercase text-5xl font-bold font-nordic">
                    CraftHub
                </h1>
                <h1 className="text-7xl font-rodabamboo">CraftConnect</h1> */}
            </main>
        </>
    );
}
